// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Articles/Article.vue')['default']
    Blob: typeof import('./src/components/Effects/Blob.vue')['default']
    CarbonBackToTop: typeof import('~icons/carbon/back-to-top')['default']
    CarbonCalendar: typeof import('~icons/carbon/calendar')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonTableOfContents: typeof import('~icons/carbon/table-of-contents')['default']
    CarbonTime: typeof import('~icons/carbon/time')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Latest: typeof import('./src/components/Articles/Latest.vue')['default']
    LinkPreview: typeof import('./src/components/Articles/LinkPreview.vue')['default']
    Navbar: typeof import('./src/components/Navigation/Navbar.vue')['default']
    Paginate: typeof import('./src/components/Pagination/Paginate.vue')['default']
    Post: typeof import('./src/components/Articles/Post.vue')['default']
    SectionTitle: typeof import('./src/components/Sections/SectionTitle.vue')['default']
    Separator: typeof import('./src/components/Articles/Separator.vue')['default']
    Share: typeof import('./src/components/Button/Share.vue')['default']
    SocialLinks: typeof import('./src/components/Sections/SocialLinks.vue')['default']
    Tag: typeof import('./src/components/Button/Tag.vue')['default']
    Techies: typeof import('./src/components/Sections/Techies.vue')['default']
    ToTopBtn: typeof import('./src/components/Button/ToTopBtn.vue')['default']
    UilGithub: typeof import('~icons/uil/github')['default']
    UilInstagram: typeof import('~icons/uil/instagram')['default']
    UilLinkedin: typeof import('~icons/uil/linkedin')['default']
    UilTwitter: typeof import('~icons/uil/twitter')['default']
    YouTube: typeof import('./src/components/Articles/YouTube.vue')['default']
  }
}

export { }
